version: '3.8'

services:

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8888:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis


  celery:
    build: ./app
    command: celery -A core worker -l INFO --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis


  dashboard:
    build: ./app
    command: celery -A core flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - celery


  redis:
    image: redis:6-alpine


  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=dating_site
      - POSTGRES_PASSWORD=dating_site
      - POSTGRES_DB=dating_site_dev


volumes:
  postgres_data:
